{"name": "Создание двух одинаковых курьеров", "status": "failed", "statusDetails": {"message": "AssertionError: assert (409 == 409 and 'Этот логин уже используется' in '{\"ok\":true}')\n +  where 409 = <Response [409]>.status_code\n +  and   'Этот логин уже используется' = CreateCourierAnswer.answer_code_409\n +  and   '{\"ok\":true}' = <Response [201]>.text", "trace": "self = <tests.test_create_courier.TestCreateCourier object at 0x00000265B59D9F40>\n\n    @allure.title(\"Создание двух одинаковых курьеров\")\n    def test_creating_two_couriers(self):\n        payload = RegisterNewCourier.register_new_courier()\n        response = requests.post(f\"{Url.PAGE_SCOOTER}{Url.CREATE_COURIER}\", data=payload)\n        response2 = requests.post(f\"{Url.PAGE_SCOOTER}{Url.CREATE_COURIER}\", data=payload)\n>       assert response2.status_code == 409 and CreateCourierAnswer.answer_code_409 in response.text\nE       assert (409 == 409 and 'Этот логин уже используется' in '{\"ok\":true}')\nE        +  where 409 = <Response [409]>.status_code\nE        +  and   'Этот логин уже используется' = CreateCourierAnswer.answer_code_409\nE        +  and   '{\"ok\":true}' = <Response [201]>.text\n\ntests\\test_create_courier.py:20: AssertionError"}, "start": 1728248146021, "stop": 1728248146332, "uuid": "626d7400-388e-417d-a2f6-058015bb349a", "historyId": "41bb3544955c887479cff07d058bc43f", "testCaseId": "41bb3544955c887479cff07d058bc43f", "fullName": "tests.test_create_courier.TestCreateCourier#test_creating_two_couriers", "labels": [{"name": "suite", "value": "Создание курьера"}, {"name": "parentSuite", "value": "tests"}, {"name": "subSuite", "value": "TestCreateCourier"}, {"name": "host", "value": "DESKTOP-COFSJ1F"}, {"name": "thread", "value": "6672-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_create_courier"}]}